version: "3.8"

services:
  api:
    build: .
    depends_on:
      - "db"
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: 'jdbc:mysql://localhost:3306/DevOps?useSSL=false'
      DATABASE_USERNAME: 'root'
      DATABASE_PASSWORD: 'santi2001'
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: 'devops'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'santi2001'
    ports:
      - "3308:3308"
    volumes:
      - db-data:/var/lib/mysql
      - ./base_de_datos.sql:/docker-entrypoint-initdb.d/base_de_datos.sql
volumes:
  db-data: